#!/bin/sh

: ${DISTRIBUTIONS="kernel.tgz world.tgz"}; export DISTRIBUTIONS
: ${BSDINSTALL_LOG="/tmp/bsdinstall_log"}; export BSDINSTALL_LOG
: ${BSDINSTALL_TMPETC="/tmp/bsdinstall_etc"}; export BSDINSTALL_TMPETC
: ${PATH_FSTAB="$BSDINSTALL_TMPETC/fstab"}; export PATH_FSTAB
: ${BSDINSTALL_DISTDIR="/usr/bsdinstall-dist"}; export BSDINSTALL_DISTDIR
: ${BSDINSTALL_CHROOT="/mnt"}; export BSDINSTALL_CHROOT

VERB=$1; shift

if [ -z $VERB ]; then
	VERB=auto
fi

exec /usr/libexec/bsdinstall/$VERB $@

