#!/bin/sh

[ -z "$DISTRIBUTIONS" ] && export DISTRIBUTIONS="kernel.tgz world.tgz"
[ -z "$BSDINSTALL_LOG" ] && export BSDINSTALL_LOG="/tmp/bsdinstall_log"
[ -z "$BSDINSTALL_TMPETC" ] && export BSDINSTALL_TMPETC="/tmp/bsdinstall_etc"
[ -z "$PATH_FSTAB" ] && export PATH_FSTAB="$BSDINSTALL_TMPETC/fstab"
[ -z "$BSDINSTALL_DISTDIR" ] && export BSDINSTALL_DISTDIR="/usr/bsdinstall-dist"
[ -z "$BSDINSTALL_CHROOT" ] && export BSDINSTALL_CHROOT="/mnt"

VERB=$1; shift

if [ -z $VERB ]; then
	VERB=auto
fi

exec /usr/libexec/bsdinstall/$VERB $@

