/*-
 * Copyright (c) 2007 Alexey Tarasov
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */

#include <stand.h>

#include "pxe_httpls.h"
#include "pxe_sock.h"

/* fgetch() - returns one char from opened file
 * in:
 *	fd - file descriptor
 * out:
 *	-1 - if failed
 *	>0 - read char
 */
int
fgetch(int fd)
{
	char	ch = 0;
	ssize_t result = read(fd, &ch, 1);	

	return (result != -1) ? ch : -1;
}

/* http_parse_index() - parses index file generated by server for directory,
 *			print result data to screen. 
 * in:
 *	fd - descriptor of file to parse
 * out:
 *	none
 */
void
http_parse_index(int fd)
{
	char	ch = 0;
	int	stream_state	= TAG_EXPECT_OPEN;
	char	tag_body[TAG_MAX_BODY] = {0};
	int	tag_size = 0;
	int	dir_listing = 0;
	
	while( (ch = fgetch(fd)) != -1) {
					
		switch(ch) {
		case '<':
			if (stream_state == TAG_EXPECT_OPEN) {
				stream_state = TAG_EXPECT_BODY;
				tag_size = 0;
				/* printf("{TEB}"); */
				continue;
			}
			break;
							
		case '>':
			if ( (stream_state == TAG_EXPECT_CLOSE) || 
			     (stream_state == TAG_EXPECT_BODY)) 
			{
				stream_state = TAG_EXPECT_OPEN;
				/* printf("{TEO}");*/
									
				/* check for <HR> */
				if (tag_size == 2) {
												
					if ( ((tag_body[0] == 'h') ||
					      (tag_body[0] == 'H')) &&
					     ((tag_body[1] == 'r') ||
					      (tag_body[1] == 'R')))
					{	/* it's <HR>, inverting dir_listing 
						 * for apache1.3 directory listing is
						 * between <hr> tags.
						 */
						dir_listing = 1 - dir_listing;	
	
						if (dir_listing == 0)
							return;
					}
				}
										
				continue;
			}
			break;
						
		case ' ': case '\t': // whitespace
			if (stream_state == TAG_EXPECT_BODY) {
				stream_state = TAG_EXPECT_CLOSE;
				/* printf("{TEC}"); */
				continue;
			}
			break;
						
		default:
			break;
		}
					
		if ( (stream_state == TAG_EXPECT_OPEN) && (dir_listing == 1))
			printf("%c", ch);
			
		if (stream_state == TAG_EXPECT_BODY) {
			if (tag_size < TAG_MAX_BODY) {
				tag_body[tag_size] = ch;
				tag_size += 1;
			} else {
				stream_state = TAG_EXPECT_CLOSE;
			}
		}
	}
}
