.\" -*- nroff -*-
.\"
.\" Copyright (c) 2016 M. Warner Losh
.\"
.\" All rights reserved.
.\"
.\" This program is free software.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE DEVELOPERS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd January 19, 2016
.Dt XPT_RELEASE_CCB 9
.Os
.Sh NAME
.Nm xpt_release_ccb
.Nd release the ccb back to the system
.Sh SYNOPSIS
.In cam/cam_xpt_periph.h
.Ft void
.Fn xpt_release_ccb "union ccb *ccb"
.Sh DESCRIPTION
The
.Nm
function releases
.Fa ccb
after the periph is done with it.
The periph should not access the contents of
.Fa ccb
after this function returns.
.Pp
The CCB
.Fa ccb
is released from the device's queue.
The periph's allocq is then run.
So, if another thread is waiting for a CCB in
.Fn cam_periph_getccb
then it will be woken up.
Otherwise, the periph's
.Fn periph_start
function will be called, perhaps multiple times.
If a CCB can't be allocated, but there are slots available in the
device's queue, a task may be scheduled to allocate the CCB, in which
case the
.Fn periph_start
routine may be called asynchronously.
.Pp
Must be called with the path lock owned.
.Sh SEE ALSO
.Xr cam_periph_getccb 9
.Sh AUTHORS
This manual page was written by
.An M. Warner Losh .
