#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netwait netoptions routing ppp stf
# REQUIRE: defaultroute resolv bridge
# REQUIRE: static_arp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
