# $FreeBSD$

MAN=	\
	apm.8 \
	apmd.8 \
	auditd.8 \
	bsnmpd.8 \
	bthidd.8 \
	cron.8 \
	devd.8 \
	ftpd.8 \
	gssd.8 \
	hastd.8 \
	hcsecd.8 \
	hostapd.8 \
	hostname.8 \
	inetd.8 \
	ip6addrctl.8 \
	ipxrouted.8 \
	kadmind.8 \
	keyserv.8 \
	kpasswdd.8 \
	lockd.8 \
	lpd.8 \
	mountd.8 \
	moused.8 \
	mroute6d.8 \
	named.8 \
	natd.8 \
	nfscbd.8 \
	nfsd.8 \
	nfsuserd.8 \
	nisdomain.8 \
	nscd.8 \
	ntpd.8 \
	ntpdate.8 \
	powerd.8 \
	ppp.8 \
	pppoed.8 \
	rarpd.8 \
	rfcomm_pppd.8 \
	route6d.8 \
	routed.8 \
	rpcbind.8 \
	rtadvd.8 \
	rtsold.8 \
	rwho.8 \
	sdpd.8 \
	sendmail.8 \
	sshd.8 \
	statd.8 \
	syslogd.8 \
	timed.8 \
	watchdogd.8 \
	ypbind.8 \
	ypserv.8 \
	ypupdated.8 \
	ypxfrd.8 \
	zfs.8

MLINKS=	zfs.8 zvol.8

MANSUBDIR=/rc.d


.include <bsd.prog.mk>
