######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 14 14:16:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../lib/ /usr/local/include/qt4 /usr/local/include/qwt6
LIBS+=	-L../../lib/libradarpkt -lpcap -lradarpkt -lqwt6

QMAKE_CFLAGS=	-g -ggdb -DATH_ENABLE_RADIOTAP_VENDOR_EXT
QMAKE_CXXFLAGS=	-g -ggdb -DATH_ENABLE_RADIOTAP_VENDOR_EXT

# Input
HEADERS += HeatMap.h MainApp.h PktSource.h
# FORMS += PlotWindow.ui MainWindow.ui
SOURCES += HeatMap.cpp MainApp.cpp PktSource.cpp main.cpp
