#!/bin/sh
#
# $FreeBSD: user/eri/pf45/head/etc/rc.d/rtsold 203433 2010-02-03 16:18:42Z ume $
#

# PROVIDE: rtsold
# REQUIRE: netif
# BEFORE: NETWORKING
# KEYWORD: nojail

. /etc/rc.subr

name="rtsold"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_postcmd="rtsold_poststart"

rtsold_poststart()
{
	# wait for DAD
	sleep $(($(${SYSCTL_N} net.inet6.ip6.dad_count) + 1))
}

load_rc_config $name
run_rc_command "$1"
