#	$FreeBSD: user/eri/pf45/head/usr.bin/bc/Makefile 202843 2010-01-22 23:19:48Z delphij $
#	$OpenBSD: Makefile,v 1.4 2006/06/30 19:02:28 otto Exp $

PROG=		bc
SRCS=		bc.y scan.l
CFLAGS+=	-I. -I${.CURDIR}

FILES+=		bc.library
FILESDIR=	${SHAREDIR}/misc

.include <bsd.prog.mk>
