# GEOM_LIBRARY_PATH

.PATH: ${.CURDIR}/../../misc

#SHLIB_NAME?=geom_${CLASS}.so
#LINKS=	${BINDIR}/geom ${BINDIR}/g${CLASS}
#SRCS+=	geom_${CLASS}.c subr.c
#CFLAGS+= -I/usr/src/sbin/geom/

CLASS=disk

.include <bsd.lib.mk>
