#!/bin/sh
#
# These are instructions for creating and populating the FBCE
# database.  Note that although this is a syntactically correct shell
# script, it will not (or at least should not) run unmodified.
#
# $FreeBSD$
#

# Initialize PostgreSQL
sudo service postgresql initdb
sudo service postgresql start

# Create a superuser for myself
sudo -u pgsql createuser -s des

# Create a regular user and database for FBCE
createuser -S -D -R fbce
createdb -E utf8 -O fbce fbce

# Create the schema
psql -f db/fbce.sql fbce fbce

# Regenerate the DBIC schema
#
# Note that this will not overwrite lib/FBCE/Model/FBCE.pm, but
# instead create lib/FBCE/Model/FBCE.pm.new.  You may replace the old
# file with the new, but you should remove the connect_info and place
# it in fbce_local.conf instead (copy the <Model::FBCE> section from
# fbce.conf and insert the correct host, user and password).
#
./db/update.sh fbce

# One-liner to set a user's password
perl -Ilib -MFBCE -e 'FBCE->model("FBCE::Person")->find({ login => "kenneth36" })->set_password("4ltInn!?")'

#
# The list of users is generated on freefall using scripts written for
# that purpose by gjb:
#
# des@freefall ~% ~gjb/bin/genuserlist.sh                          
# Output written to: /home/des/tmp.NAQqdhqXM0
# des@freefall ~% ~gjb/bin/genuserlist.pl /home/des/tmp.NAQqdhqXM0 >users-20140521.txt
# des@freefall ~% echo dbn >>users-20140521.txt
# des@freefall ~% getent passwd $(cat users-20140521.txt) >gecos-20140521.txt
#
./script/fbce_user.pl import users-20140521.txt
./script/fbce_user.pl gecos gecos-20140521.txt
./script/fbce_user.pl smash

#
# The list of active committers is extracted from fst3k:
#
# fst3k=# \t on
# Showing only tuples.
# fst3k=# \o active-20140521.txt
# fst3k=# select p.login from persons p join revisions r on p.id = r.author where r.datetime >= '2013-05-21' group by p.login;
#
./script/fbce_user.pl activate active-20140521.txt

#
# The list of incumbents was manually generated from
# http://www.freebsd.no/administration.html#t-core
#
./script/fbce_user.pl incumbent core-20140521.txt

#
# Finally, generate passwords
#
./script/fbce_user.pl pwgen

# Print the logins of active users who haven't voted
perl -Ilib -MFBCE -e 'map { print $_->login, "\n" } grep { $_->active && $_->votes_voters->count == 0 } FBCE->model("FBCE::Person")->all'
