#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: user/eri/pf45/head/share/doc/usd/05.dc/Makefile 202843 2010-01-22 23:19:48Z delphij $

VOLUME=	usd/05.dc
SRCS=	dc
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.bin/dc/USD.doc

.include <bsd.doc.mk>
