#!/bin/sh

dialog --backtitle "FreeBSD Installer" --title "Add User Accounts" --yesno \
    "Would you like to add users to the installed system now?" 0 0

if [ $? -eq 0 ]; then
	clear
	echo "FreeBSD Installer"
	echo "========================"
	echo "Add Users"
	echo
	chroot $BSDINSTALL_CHROOT adduser
fi
