#!/bin/sh

echo "Begun Installation at $(date)" > $BSDINSTALL_LOG

cdialog --backtitle "FreeBSD Installer" --title "Welcome" --msgbox "Welcome to the FreeBSD Installer." 0 0

bsdinstall hostname

FETCH_DISTRIBUTIONS=""
for dist in $DISTRIBUTIONS; do
	if [ ! -f $BSDINSTALL_DISTDIR/$dist.tgz ]; then
		FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
	fi
done

if [ ! -z "$FETCH_DISTRIBUTIONS" ]; then
	cdialog --backtitle "FreeBSD Installer" --title "Network Installation" --msgbox "No installation files were found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
	bsdinstall netconfig mirrorselect
fi

rm $PATH_FSTAB
rm /tmp/rc.conf
bsdinstall partedit
bsdinstall mount 

if [ ! -z $FETCH_DISTRIBUTIONS ]; then
	ALL_DISTRIBUTIONS=$DISTRIBUTIONS
	DISTRIBUTIONS=$FETCH_DISTRIBUTIONS
	bsdinstall distfetch
	DISTRIBUTIONS=$ALL_DISTRIBUTIONS
fi

bsdinstall distextract
bsdinstall config 
#bsdinstall rootpass

cdialog --backtitle "FreeBSD Installer" --title "Welcome" --msgbox "Installation of FreeBSD complete!" 0 0

echo "Installation Completed at $(date)" >> $BSDINSTALL_LOG

