#!/bin/sh

echo "Begun Installation at $(date)" > $BSDINSTALL_LOG

cdialog --backtitle "FreeBSD Installer" --title "Welcome" --msgbox "Welcome to the FreeBSD Installer." 0 0

checkerror() {
	if [ $? -ne 0 ]; then
		cdialog --backtitle "FreeBSD Installer" --title "Abort" \
		    --no-label "Exit" --yes-label "Restart" --yesno \
		    "You have canceled an installation step. Would you like to restart the installation or exit the installer?" 0 0
		if [ $? -ne 0 ]; then
			exit
		else
			exec $0 $@
		fi
	fi
}

rm /tmp/rc.conf
bsdinstall hostname
checkerror

FETCH_DISTRIBUTIONS=""
for dist in $DISTRIBUTIONS; do
	if [ ! -f $BSDINSTALL_DISTDIR/$dist ]; then
		FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
	fi
done

if [ ! -z "$FETCH_DISTRIBUTIONS" ]; then
	cdialog --backtitle "FreeBSD Installer" --title "Network Installation" --msgbox "No installation files were found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
	bsdinstall netconfig
	checkerror
fi

rm $PATH_FSTAB
bsdinstall partedit
checkerror
bsdinstall mount 

if [ ! -z $FETCH_DISTRIBUTIONS ]; then
	ALL_DISTRIBUTIONS=$DISTRIBUTIONS
	DISTRIBUTIONS=$FETCH_DISTRIBUTIONS
	bsdinstall distfetch
	checkerror
	DISTRIBUTIONS=$ALL_DISTRIBUTIONS
fi

bsdinstall distextract
checkerror
bsdinstall rootpass
checkerror
bsdinstall adduser
checkerror
bsdinstall config 
checkerror

cdialog --backtitle "FreeBSD Installer" --title "Complete" --msgbox "Installation of FreeBSD complete!" 0 0

echo "Installation Completed at $(date)" >> $BSDINSTALL_LOG

