#!/bin/sh
#
# buildsuccess <arch> <branch> <buildid> <pkgname>

# configurable variables
pbc=${PORTBUILD_CHECKOUT:-/var/portbuild}
pbd=${PORTBUILD_DATA:-/var/portbuild}

usage () {
  echo "usage: buildsuccess arch branch buildid pkgname"
  exit 1
}

if [ $# -ne 4 ]; then
  usage
fi

arch=$1
branch=$2
buildid=$3
pkgname=$4
shift 4

builddir=${pbd}/${arch}/${branch}/builds/${buildid}

. ${pbc}/conf/server.conf
. ${pbc}/conf/common.conf
. ${pbd}/${arch}/portbuild.conf
if [ -f ${pbd}/${arch}/${branch}/builds/${buildid}/portbuild.conf ]; then
    . ${pbd}/${arch}/${branch}/builds/${buildid}/portbuild.conf
fi
. ${pbc}/scripts/buildenv

buildenv ${pbd} ${arch} ${branch} ${builddir}

# Don't pick up installed packages from the host
export LOCALBASE=/nonexistentlocal

index=${PORTSDIR}/${INDEXFILE}

portloc=$(grep "^$pkgname|" ${index} | cut -f 2 -d \| | sed s,/usr/ports/,,)

cd ${pbd}/${arch}/${branch}
if grep -q "^${portloc}|" failure; then
    echo | mail -s "${pkgname} now builds on ${arch} ${branch}" ${mailto}
    grep -v "^${portloc}|" failure > failure.new
    mv failure.new failure
fi

if [ -L ${pbd}/${arch}/${branch}/latest/${portloc} ]; then
    rm -f ${pbd}/${arch}/${branch}/latest/${portloc}
fi
