#!/bin/sh

# configurable variables
pbd=${PORTBUILD_DATA:-/var/portbuild}

. ${pbd}/portbuild.conf

lock=${pbd}/cppackages.lock

unset DISPLAY

echo "Subject: package copying logs"
echo
echo "Called with arguments: "${1+"$@"}
echo "Started at $(date)"

if [ $# != 1 ]; then
  echo "usage: $0 branch"
  exit 1
fi

if [ -e ${lock} ]; then
  echo "Skipped since lock file exists"
  exit 1
fi

touch ${lock}

cd $pb
tar -cf - $1/packages | ssh $ftpsite -l $user tar -C $packagedir -xvf - 2>&1 | tail -100

echo "Ended at $(date)"

rm -f ${lock}
