#!/bin/sh
# 
# clean up stale chroots on all client machines.
#

pbc=${PORTBUILD_CHECKOUT:-/a/portbuild}

arch=$1
if [ -z "$arch" ]; then
  arch=all
fi
${pbc}/scripts/allgohans ${arch} -q -scp ${pbc}/scripts/cleanup-chroots
