#!/bin/sh
# 
# clean up stale /tmp on all client machines.
#

pbc=${PORTBUILD_CHECKOUT:-/a/portbuild}

arch=$0
if [ -z "$arch" ]; then
  arch=all
fi
${pbc}/scripts/allgohans ${arch} -q -scp ${pbc}/scripts/cleanup-tmp
