#!/bin/sh

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}

exec 3>&1
HOSTNAME=`cdialog --backtitle 'FreeBSD Installer' --title 'Set Hostname' --nocancel --inputbox \
	'Please choose a hostname for this machine.

If you are running on a managed network, please ask your network administrator for an appropriate name.' \
	0 0 $(hostname) 2>&1 1>&3`
if [ $? -eq $DIALOG_CANCEL ]; then exec $0; fi
exec 3>&-

echo "hostname=\"$HOSTNAME\"" >> /tmp/rc.conf
