#!/bin/sh

echo "Begun Installation at $(date)" > $BSDINSTALL_LOG

export BSDINSTALL_CHROOT=$1
export DISTRIBUTIONS="`echo $DISTRIBUTIONS | sed 's/kernel\.[^ ]* //g'`"

error() {
	dialog --backtitle "FreeBSD Installer" --title "Abort" \
	    --no-label "Exit" --yes-label "Restart" --yesno \
	    "You have canceled an installation step. Would you like to restart the installation or exit the installer?" 0 0
	if [ $? -ne 0 ]; then
		exit
	else
		test -f $PATH_FSTAB && bsdinstall umount
		exec $0
	fi
}


rm -rf $BSDINSTALL_TMPETC
mkdir $BSDINSTALL_TMPETC

trap error SIGINT	# SIGINT is bad

FETCH_DISTRIBUTIONS=""
for dist in $DISTRIBUTIONS; do
	if [ ! -f $BSDINSTALL_DISTDIR/$dist ]; then
		FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
	fi
done

if [ ! -z $FETCH_DISTRIBUTIONS ]; then
	ALL_DISTRIBUTIONS=$DISTRIBUTIONS
	DISTRIBUTIONS=$FETCH_DISTRIBUTIONS
	bsdinstall distfetch || error
	DISTRIBUTIONS=$ALL_DISTRIBUTIONS
fi

bsdinstall distextract || error
bsdinstall rootpass || error

trap true SIGINT	# This section is optional
bsdinstall time
bsdinstall services

dialog --backtitle "FreeBSD Installer" --title "Add User Accounts" --yesno \
    "Would you like to add users to the installed system now?" 0 0 && \
    bsdinstall adduser

trap error SIGINT	# SIGINT is bad again
bsdinstall config  || error

echo "Installation Completed at $(date)" >> $BSDINSTALL_LOG

