#!/bin/sh
# $FreeBSD: ports/Tools/portbuild/scripts/keeprestr,v 1.3 2010/06/25 22:49:56 linimon Exp $

# server-side script to save off RESTRICTED files

usage () {
  echo "usage: keeprestr arch branch buildid"
  exit 1
}

if [ $# -ne 3 ]; then
  usage
fi

arch=$1
branch=$2
buildid=$3

pbc=${PORTBUILD_CHECKOUT:-/var/portbuild}
pbd=${PORTBUILD_DATA:-/var/portbuild}

. ${pbc}/conf/server.conf
. ${pbc}/scripts/buildenv

buildid=$(resolve ${pbd} ${arch} ${branch} ${buildid})
if [ -z "${buildid}" ]; then
    echo "Invalid build ID ${buildid}"
    exit 1
fi

builddir=${pbd}/${arch}/${branch}/builds/${buildid}
cd ${builddir}

rm -rf bak/restricted
mkdir -p bak/restricted

(tr ';' '\n' < restricted.sh | grep "/bin/rm -f" | awk '{print $3}' | grep packages/ | sed -e "s,${builddir}/,," -e 's,)$,,' | xargs ls -1 2>/dev/null) | cpio -dumpl bak/restricted/

