#!/bin/sh
# usage: $0 arch branch buildid

# Don't want to pick up host customizations
export INDEX_PRISTINE=1

# Don't give luser advice if it fails
export INDEX_QUIET=1

# Concurrency of index build
export INDEX_JOBS=6

# For debugging purposes only
#export INDEX_VERBOSE=1

pb=/var/portbuild

usage () {
  echo "usage: makeindex arch branch buildid [target]"
  exit 1
}

if [ $# -lt 3 ]; then
  usage
fi

arch=$1
branch=$2
buildid=$3
target=$4

builddir=${pb}/${arch}/${branch}/builds/${buildid}

. ${pb}/conf/server.conf
. ${pb}/conf/common.conf
. ${pb}/${arch}/portbuild.conf
. ${pb}/scripts/buildenv

# Set up the build env variables
buildenv ${pb} ${arch} ${branch} ${builddir}

unset DISPLAY

# Don't pick up installed packages from the host
export LOCALBASE=/nonexistentlocal

if [ -n "$target" ]; then
  if [ -f "$target" ]; then
    INDEX_PORTS=$(cat $target | tr '\n' ' ')
  else
    echo "File $target doesn't exist. Exiting."
    exit 1
  fi
fi

cd ${PORTSDIR}
make index INDEX_PORTS="${INDEX_PORTS}"
if [ ! -e ${INDEXFILE} ]; then
  echo "makeindex: failed to make ${INDEXFILE}"
  exit 1
fi

# remove extra spaces in dependency list -- this causes problems
# Also transform the dummy paths to their canonical locations
sed -i '' -e 's/  */ /g' -e 's/|  */|/g' -e 's/  *|/|/g' -e "s,${LOCALBASE},/usr/local," ${INDEXFILE}
