#!/bin/sh

cat $PATH_FSTAB | awk -v BSDINSTALL_CHROOT=$BSDINSTALL_CHROOT '{
	if ($2 ~ "^/.*") {
		fsname = $2;
		if (fsname == "/")
			fsname = ""
		printf("%s\t%s%s\t%s\t%s\t%s\t%s\n", $1, BSDINSTALL_CHROOT, 
		    fsname, $3, $4, $5, $6);
	}
}' > $PATH_FSTAB.tmp

FILESYSTEMS=`cat $PATH_FSTAB.tmp | awk '/^[^#].*/ {if ($2 ~ "^/.*") printf("%s\n", $2);}' | sort -t /`

for i in $FILESYSTEMS; do
	mkdir $i 2>/dev/null
	MNTERROR=`mount -F $PATH_FSTAB.tmp $i 2>&1`
	if [ $? -ne 0 ]; then
		cdialog --backtitle "FreeBSD Installer" --title "Error" \
		    --msgbox "Error mounting partition $i:\n$MNTERROR" 0 0
		exit 1
	fi
done
