#!/bin/sh

if [ -f $BSDINSTALL_TMPETC/rc.conf.services ]; then
	eval `sed -e s/YES/on/I -e s/NO/off/I $BSDINSTALL_TMPETC/rc.conf.services`
else
	# Default service states. Everything is off if not enabled.
	sshd_enable="on"
fi

echo -n > $BSDINSTALL_TMPETC/rc.conf.services

exec 3>&1
DAEMONS=$(dialog --backtitle "FreeBSD Installer" \
    --title "System Configuration" --nocancel --separate-output \
    --checklist "Choose the services you would like to be started at boot:" \
    0 0 0 \
	sshd	"Secure shell daemon" ${sshd_enable:-off} \
	moused	"PS/2 mouse pointer on console" ${moused_enable:-off} \
	ntpd	"Synchronize system and network time" ${ntpd_enable:-off} \
	powerd	"Adjust CPU frequency dynamically" ${powerd_enable:-off} \
2>&1 1>&3)
exec 3>&-

for daemon in $DAEMONS; do
	echo ${daemon}_enable=\"YES\" >> $BSDINSTALL_TMPETC/rc.conf.services
done

