#!/bin/sh

pbc=${PORTBUILD_CHECKOUT:-/a/portbuild}
pbd=${PORTBUILD_DATA:-/a/portbuild}

. ${pbc}/admin/conf/admin.conf
. ${pbc}/conf/server.conf

if [ $# -ne 1 ]; then
	echo "usage: <branch>"
	exit 1
fi

branch=$1

for i in ${SUPPORTED_ARCHS}; do
	all=${pbd}/$i/${branch}/builds/latest/packages/All
	if [ -d ${all} ]; then
		count=$(find ${all} -name '*.t[bgx]z' | wc -l)
		echo -n "$i: ${count}  "
	fi
done
echo
