#!/bin/sh

pbc=${PORTBUILD_CHECKOUT:-/var/portbuild}
pbd=${PORTBUILD_DATA:-/var/portbuild}

. ${pbc}/conf/server.conf

if [ $# -ne 1 ]; then
	echo "usage: <branch>"
	exit 1
fi

branch=$1

for i in ${SUPPORTED_ARCHS}; do
	all=${pbd}/$i/${branch}/builds/latest/packages/All
	if [ -d ${all} ]; then
		count=$(find ${all} -name \*.tbz -o -name \*.tgz |wc -l)
		echo -n "$i: ${count}  "
	fi
done
echo
