#!/bin/sh

TMP_FSTAB=/tmp/bsdinstall-tmp-fstab

cat $PATH_FSTAB | awk -v BSDINSTALL_CHROOT=$BSDINSTALL_CHROOT '{
	if ($2 ~ "^/.*") {
		fsname = $2;
		if (fsname == "/")
			fsname = ""
		printf("%s\t%s%s\t%s\t%s\t%s\t%s\n", $1, BSDINSTALL_CHROOT, 
		    fsname, $3, $4, $5, $6);
	}
}' > $TMP_FSTAB

umount $BSDINSTALL_CHROOT/dev 2>/dev/null
umount -F $TMP_FSTAB -a 2>/dev/null
