#!/bin/sh
#
# Update the master source trees that are used by package builds
# and other consumers

pbc=${PORTBUILD_CHECKOUT:-/var/portbuild}

. ${pbc}/conf/server.conf

base=${ZFS_MOUNTPOINT}/${SNAP_DIRECTORY}
zbase=${ZFS_VOLUME}/${SNAP_DIRECTORY}
base_prefix=${ZFS_MOUNTPOINT}/${SNAP_DIRECTORY}/${SRC_DIRECTORY_PREFIX}
zbase_prefix=${ZFS_VOLUME}/${SNAP_DIRECTORY}/${SRC_DIRECTORY_PREFIX}

VERBOSE=1

# XXX MCL 20121115 try to switch to SVN
#supstamp() {
#	fulldate=$1
#        date -j -f %+ "${fulldate}" +%Y.%m.%d.%H.%M.%S
#}
# XXX MCL 20121115 try to switch to SVN

stamp() {
	fulldate=$1
        date -j -f %+ "${fulldate}" +%Y%m%d%H%M%S
}

finish() {
    err=$1

    end=$(date +%s)
    echo "Finished at $(date)"
    len=$((end-begin))
    echo "Duration = $(date -j -f %s +%H:%M:%S ${len})"
    exit 1
}

begin=$(date +%s)
echo "Started at $(date)"

# We need to preserve group writability so portmgr group can write
umask 002

# create /a/snap if not already there
if [ ! -d ${base} ]; then
  echo "creating new base directory using ${base}"
  mkdir -p ${base} || finish 1
  echo "zfs create -o mountpoint=${base} ${zbase}"
  zfs create -o mountpoint=${base} ${zbase} || finish 1
  chown -R portmgr:portmgr ${base}
  chmod -R g+w ${base}
fi

for branch in $SRC_BRANCHES; do
  mountpoint=${base_prefix}${branch}
  # create /a/snap/src-<branch> if not already there
  if [ ! -d ${mountpoint} ]; then
    echo "creating new source branch using ${mountpoint}"
    mkdir ${mountpoint} || finish 1
    echo "zfs create -o mountpoint=${mountpoint} ${zbase_prefix}${branch}"
    zfs create -o mountpoint=${mountpoint} ${zbase_prefix}${branch} || finish 1
    chown -R portmgr:portmgr ${mountpoint}
    chmod -R g+w ${mountpoint}
  fi
  # create /a/snap/src-<branch>/src if not already there
  if [ ! -d ${mountpoint}/src ]; then
    echo "creating new source branch subdirectory using ${mountpoint}/src"
    mkdir ${mountpoint}/src || finish 1
    echo "zfs create -o mountpoint=${mountpoint}/src ${zbase_prefix}${branch}/src"
    zfs create -o mountpoint=${mountpoint}/src ${zbase_prefix}${branch}/src || finish 1
    chown -R portmgr:portmgr ${mountpoint}/src
    chmod -R g+w ${mountpoint}/src
  fi
  cd ${mountpoint}
  fulldate=$(date)
# XXX MCL 20121115 try to switch to SVN
#  supdate=$(supstamp ${fulldate})
#  eval tag=\$SRC_BRANCH_${branch}_TAG
#  if [ ! -f ${SRC_MASTER_SUPFILE} ]; then
#    echo "${SRC_MASTER_SUPFILE} does not exist!"
#  else
#    sed "s|%%DATE%%|${supdate}|;s|%%PREFIX%%|${mountpoint}|;s|%%TAG%%|${tag}|" \
#      ${SRC_MASTER_SUPFILE} > ${SRC_SUPFILE}.${branch}.now
#    # example destination directory: /a/snap/src-7/src/ (tricky!)
#    if [ $VERBOSE ]; then
#      echo "csup -L 2 ${SRC_SUPFILE}.${branch}.now > src-csup.${branch}.log"
#    fi
#    csup -L 2 ${SRC_SUPFILE}.${branch}.now > src-csup.${branch}.log
# XXX MCL 20121115 try to switch to SVN
    # example destination directory: /a/snap/src-7/src/ (tricky!)
    echo "XXX now at `pwd -P`"
    if [ ! -d ${mountpoint}/src ]; then
      mkdir ${mountpoint}/src || finish 1
    fi
    if [ ! -d .svn ]; then
      if [ $VERBOSE ]; then
        # XXX MCL 20121115 gotta do the substitution here!
        echo "svn checkout svn+ssh://svn.freebsd.org/base/head ${mountpoint}/src"
      fi
      #svn checkout svn+ssh://svn.freebsd.org/base/head ${mountpoint}/src || finish 1
    else
      if [ $VERBOSE ]; then
        echo "svn up"
      fi
      #svn up || finish 1
    fi
# XXX MCL 20121115 try to switch to SVN
    echo ${fulldate} > src/.updated
    # hack for zfs breakiness
    find . -group wheel|xargs chgrp portmgr
    snapdate=$(stamp ${fulldate})
    if [ $VERBOSE ]; then
      echo "#zfs snapshot ${zbase_prefix}${branch}/src@${snapdate}"
    fi
    #zfs snapshot ${zbase_prefix}${branch}/src@${snapdate} || finish 1
# XXX MCL 20121115 try to switch to SVN
#  fi
# XXX MCL 20121115 try to switch to SVN
done

finish 0
