#!/bin/sh
#
# Update the master source trees that are used by package builds
# and other consumers

pbc=${PORTBUILD_CHECKOUT:-/var/portbuild}

. ${pbc}/conf/server.conf

base=${ZFS_MOUNTPOINT}/${SNAP_DIRECTORY}
zbase=${ZFS_VOLUME}/${SNAP_DIRECTORY}
base_prefix=${ZFS_MOUNTPOINT}/${SNAP_DIRECTORY}/${SRC_DIRECTORY_PREFIX}
zbase_prefix=${ZFS_VOLUME}/${SNAP_DIRECTORY}/${SRC_DIRECTORY_PREFIX}

VERBOSE=1

stamp() {
	fulldate=$1
        date -j -f %+ "${fulldate}" +%Y%m%d%H%M%S
}

finish() {
    err=$1

    end=$(date +%s)
    echo "Finished at $(date)"
    len=$((end-begin))
    echo "Duration = $(date -j -f %s +%H:%M:%S ${len})"
    exit 1
}

begin=$(date +%s)
echo "Started at $(date)"

# We need to preserve group writability
umask 002

uid=${PORTBUILD_USER}
if [ ! -z "${PORTBUILD_GROUP}" ]; then
    gid=${PORTBUILD_GROUP}
else
    gid=${uid}
fi

# create /a/snap if not already there
if [ ! -d ${base} ]; then
  echo "creating new base directory using ${base}"
  mkdir -p ${base} || finish 1
  echo "zfs create -o mountpoint=${base} ${zbase}"
  zfs create -o mountpoint=${base} ${zbase} || finish 1
  chown -R ${uid}:${gid} ${base}
  chmod -R g+w ${base}
fi

for branch in $SRC_BRANCHES; do
  mountpoint=${base_prefix}${branch}
  # create /a/snap/src-<branch> if not already there
  if [ ! -d ${mountpoint} ]; then
    echo "creating new source branch using ${mountpoint}"
    mkdir ${mountpoint} || finish 1
    echo "zfs create -o mountpoint=${mountpoint} ${zbase_prefix}${branch}"
    zfs create -o mountpoint=${mountpoint} ${zbase_prefix}${branch} || finish 1
    chown -R ${uid}:${gid} ${mountpoint}
    chmod -R g+w ${mountpoint}
  fi
  # create /a/snap/src-<branch>/src if not already there
  if [ ! -d ${mountpoint}/src ]; then
    echo "creating new source branch subdirectory using ${mountpoint}/src"
    mkdir ${mountpoint}/src || finish 1
    echo "zfs create -o mountpoint=${mountpoint}/src ${zbase_prefix}${branch}/src"
    zfs create -o mountpoint=${mountpoint}/src ${zbase_prefix}${branch}/src || finish 1
    chown -R ${uid}:${gid} ${mountpoint}/src
    chmod -R g+w ${mountpoint}/src
  fi
  cd ${mountpoint}
  fulldate=$(date)

    # TODO: fix identation post-rework

    # example destination directory: /a/snap/src-7/src/ (tricky!)
    if [ ! -d ${mountpoint}/src ]; then
      mkdir ${mountpoint}/src || finish 1
    fi
    if [ ! -d ${mountpoint}/src/${VCS_SUBDIR} ]; then
      eval subdir=\$SRC_BRANCH_${branch}_SUBDIR
      if [ $VERBOSE ]; then
        echo "${VCS_CHECKOUT_COMMAND} ${VCS_SRC_REPOSITORY}/${subdir} ${mountpoint}/src"
      fi
      ${VCS_CHECKOUT_COMMAND} ${VCS_SRC_REPOSITORY}/${subdir} ${mountpoint}/src || finish 1
    else
      if [ $VERBOSE ]; then
        echo "${VCS_UPDATE_COMMAND} ${mountpoint}/src"
      fi
      ${VCS_UPDATE_COMMAND} ${mountpoint}/src || finish 1
    fi
    echo ${fulldate} > src/.updated
    # hack for zfs breakiness
    find . -group wheel | xargs chgrp ${gid}
    snapdate=$(stamp ${fulldate})
    if [ $VERBOSE ]; then
      echo "zfs snapshot ${zbase_prefix}${branch}/src@${snapdate}"
    fi
    zfs snapshot ${zbase_prefix}${branch}/src@${snapdate} || finish 1
done

finish 0
