package FBCE::Model::FBCE;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'FBCE::Schema',
    
    
);

=head1 NAME

FBCE::Model::FBCE - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<FBCE>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<FBCE::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Dag-Erling Smørgrav

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
