# $FreeBSD$

CCLN=           be_BY bg_BG ca_ES cs_CZ de_DE el_GR es_ES et_EE \
		hi_IN hr_HR hy_AM is_IS kk_KZ la_LN lt_LT no_NO pl_PL \
		ru_RU sl_SI sr_Cyrl_RS sv_SE tr_TR uk_UA

# For these locales, beside creating the UTF-8 map also create these
# charactermaps.
CMS_be_BY=	CP1131 CP1251 ISO8859-5
CMS_bg_BG=	CP1251
CMS_ca_ES=	ISO8859-1 ISO8859-15
CMS_cs_CZ=	ISO8859-2
CMS_de_DE=	ISO8859-1 ISO8859-15
CMS_el_GR=	ISO8859-7
CMS_es_ES=	ISO8859-1 ISO8859-15
CMS_et_EE=	ISO8859-15
CMS_hi_IN=	ISCII-DEV
CMS_hr_HR=	ISO8859-2
CMS_hy_AM=	ARMSCII-8
CMS_is_IS=	ISO8859-1 ISO8859-15
CMS_kk_KZ=	PT154
CMS_la_LN=	ISO8859-1 ISO8859-2 ISO8859-4 ISO8859-13 ISO8859-15 US-ASCII
CMS_lt_LT=	ISO8859-4
CMS_no_NO=	ISO8859-1 ISO8859-15
CMS_pl_PL=	ISO8859-2
CMS_ru_RU=	CP1251 CP866 ISO8859-5 KOI8-R
CMS_sl_SI=	ISO8859-2
CMS_sr_Cyrl_RS=	ISO8859-5
CMS_sv_SE=	ISO8859-1 ISO8859-15
CMS_tr_TR=	ISO8859-9
CMS_uk_UA=	CP1251 ISO8859-5 KOI8-U

# For these locales, link the following charactermaps to the UTF-8 map.
# (unless the origin charactermap is defined)
CMSLINK_ca_ES.ISO8859-1=	ca_AD.ISO8859-1 ca_FR.ISO8859-1 ca_IT.ISO8859-1
CMSLINK_ca_ES.ISO8859-15=	ca_AD.ISO8859-15 ca_FR.ISO8859-15 ca_IT.ISO8859-15
CMSLINK_cs_CZ.ISO8859-2=	sk_SK.ISO8859-2
CMSLINK_de_DE.ISO8859-1=	de_AT.ISO8859-1 de_CH.ISO8859-1
CMSLINK_de_DE.ISO8859-15=	de_AT.ISO8859-15 de_CH.ISO8859-15
CMSLINK_is_IS.ISO8859-1=	zh_Hant_TW.Big5
CMSLINK_no_NO.ISO8859-1=	nb_NO.ISO8859-1 nn_NO.ISO8859-1
CMSLINK_no_NO.ISO8859-15=	nb_NO.ISO8859-15 nn_NO.ISO8859-15
CMSLINK_pt_PT.ISO8859-1=	pt_BR.ISO8859-1
CMSLINK_la_LN.ISO8859-1=	af_ZA.ISO8859-1 da_DK.ISO8859-1 en_AU.ISO8859-1 en_CA.ISO8859-1 en_GB.ISO8859-1 en_NZ.ISO8859-1 en_US.ISO8859-1 eu_ES.ISO8859-1 fi_FI.ISO8859-1 fr_BE.ISO8859-1 fr_CA.ISO8859-1 fr_CH.ISO8859-1 fr_FR.ISO8859-1 it_CH.ISO8859-1 it_IT.ISO8859-1 nl_BE.ISO8859-1 nl_NL.ISO8859-1 pt_BR.ISO8859-1 pt_PT.ISO8859-1
CMSLINK_la_LN.ISO8859-2=	hu_HU.ISO8859-2 ro_RO.ISO8859-2 sr_YU.ISO8859-2	
CMSLINK_la_LN.ISO8859-13=	lt_LT.ISO8859-13 lv_LV.ISO8859-13
CMSLINK_la_LN.ISO8859-15=	af_ZA.ISO8859-15 da_DK.ISO8859-15 en_AU.ISO8859-15 en_CA.ISO8859-15 en_GB.ISO8859-15 en_NZ.ISO8859-15 en_US.ISO8859-15 eu_ES.ISO8859-15 fi_FI.ISO8859-15 fr_BE.ISO8859-15 fr_CA.ISO8859-15 fr_CH.ISO8859-15 fr_FR.ISO8859-15 it_CH.ISO8859-15 it_IT.ISO8859-15 nl_BE.ISO8859-15 nl_NL.ISO8859-15 pt_PT.ISO8859-15
CMSLINK_la_LN.US-ASCII=		af_ZA.UTF-8 am_ET.UTF-8 be_BY.UTF-8 bg_BG.UTF-8 ca_AD.UTF-8 ca_ES.UTF-8 ca_FR.UTF-8 ca_IT.UTF-8 cs_CZ.UTF-8 da_DK.UTF-8 de_AT.UTF-8 de_CH.UTF-8 de_DE.UTF-8 el_GR.UTF-8 en_AU.US-ASCII en_AU.UTF-8 en_CA.US-ASCII en_CA.UTF-8 en_GB.US-ASCII en_GB.UTF-8 en_IE.UTF-8 en_NZ.US-ASCII en_NZ.UTF-8 en_US.US-ASCII en_US.UTF-8 es_ES.UTF-8 et_EE.UTF-8 eu_ES.UTF-8 fi_FI.UTF-8 fr_BE.UTF-8 fr_CA.UTF-8 fr_CH.UTF-8 fr_FR.UTF-8 he_IL.UTF-8 hr_HR.UTF-8 hu_HU.UTF-8 hy_AM.UTF-8 is_IS.UTF-8 it_CH.UTF-8 it_IT.UTF-8 ja_JP.SJIS ja_JP.UTF-8 ja_JP.eucJP kk_KZ.UTF-8 ko_KR.CP949 ko_KR.UTF-8 ko_KR.eucKR lt_LT.UTF-8 lv_LV.UTF-8 mn_MN.UTF-8 nb_NO.UTF-8 nl_BE.UTF-8 nl_NL.UTF-8 nn_NO.UTF-8 no_NO.UTF-8 pl_PL.UTF-8 pt_BR.UTF-8 pt_PT.UTF-8 ro_RO.UTF-8 ru_RU.UTF-8 sk_SK.UTF-8 sl_SI.UTF-8 sr_YU.UTF-8 sv_SE.UTF-8 tr_TR.UTF-8 uk_UA.UTF-8 zh_Hans_CN.GB18030 zh_Hans_CN.GB2312 zh_Hans_CN.GBK zh_Hans_CN.UTF-8 zh_Hans_CN.eucCN zh_Hant_HK.Big5HKSCS zh_Hant_HK.UTF-8 zh_Hant_TW.UTF-8

# For these locales, also create symlinks to the main locale.
#CCLNLINK_ccln=	ccnln
# None!

# For these locales, create symlinks to the main locale for historical reasons.
# The ones for zh_XX are linked to la_LN because there are no
# zh_Hanx_XX CCLN entries.
LEGLINK_sr_Cyrl_RS.ISO8859-5=	sr_YU.ISO8859-5
LEGLINK_sr_Latn_RS=	sr_YU
LEGLINK_ja_JP=	jp_JP
#EGLINK_zh_Hant_TW=	zh_TW
LEGLINK_la_LN.US-ASCII+=	zh_TW.UTF-8
LEGLINK_is_IS.ISO8859-1+=	zh_TW.Big5
#EGLINK_zh_Hant_HK=	zh_HK
LEGLINK_la_LN.US-ASCII+=	zh_HK.UTF-8 zh_HK.Big5HKSCS
#EGLINK_zh_Hans_CN=	zh_CN
LEGLINK_la_LN.US-ASCII+=	zh_CN.eucCN zh_CN.UTF-8 zh_CN.GBK zh_CN.GB2312 zh_CN.GB18030

#
# In theory there are no parts after here which should be touched when adding
# or removing locales and charactermaps.
#

# Required variables
LCTYPE=		LC_COLLATE
LOCALEDIR=	/usr/share/locale

# DONE
#
# All variables
#

.include "../Makefile.def.inc"
.include <bsd.prog.mk>
