# $FreeBSD: user/eri/pf45/head/tools/regression/kqueue/Makefile 200483 2009-12-13 20:27:46Z rwatson $
#
# svn://mark.heily.com/libkqueue/trunk/test
# Last update: r114
#
# libkqueue and test suite by Mark Heily <mark@heily.com>
#

PROG=kqtest
SRCS=			\
	main.c		\
	read.c		\
	timer.c		\
	vnode.c		\
	proc.c		\
	signal.c	\
	user.c
NO_MAN=
WARNS=2

.include "bsd.prog.mk"
