#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: user/eri/pf45/head/share/doc/usd/06.bc/Makefile 202843 2010-01-22 23:19:48Z delphij $

VOLUME=	usd/06.bc
SRCS=	bc
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.bin/bc/USD.doc

.include <bsd.doc.mk>
