# $FreeBSD$

SUBDIR=		mbr pmbr boot0 boot0sio btx boot2 cdboot gptboot \
		kgzldr libi386 libfirewire loader

# SUBDIR+= zfsboot

# special boot programs, 'self-extracting boot2+loader'
SUBDIR+=	pxeldr

.include <bsd.subdir.mk>
